import { test, expect } from "./fixtures";
import { addAndStart } from "./helpers";

test("A and B remain resumable after switching to C, then pause, complete and copy history", async ({ page, context }) => {
    await page.goto("/");
    await addAndStart(page, "A 작업");
    await addAndStart(page, "B 요청");
    await addAndStart(page, "C 요청");
    const interrupted = page.getByRole("region", { name: "하다 만 작업" });
    await expect(interrupted).toContainText("A 작업");
    await expect(interrupted).toContainText("B 요청");
    await page.getByRole("button", { name: "A 작업 이어 하기" }).click();
    const current = page.getByRole("region", { name: "지금 하는 일" });
    await expect(current).toContainText("A 작업");
    await page.getByRole("button", { name: "잠시 멈추기" }).click();
    await expect(current).toContainText("지금 하는 일 없음");
    await expect(interrupted).toContainText("A 작업");
    await page.getByRole("button", { name: "A 작업 이어 하기" }).click();
    await page.getByRole("button", { name: "완료", exact: true }).click();
    await expect(current).toContainText("지금 하는 일 없음");
    await expect(interrupted).not.toContainText("A 작업");
    await page.reload();
    await expect(interrupted).toContainText("B 요청");
    await expect(interrupted).toContainText("C 요청");
    await page.getByRole("button", { name: "기록", exact: true }).click();
    const records = page.getByRole("list", { name: "작업별 기록" });
    await expect(records).toContainText("A 작업");
    await expect(records.getByRole("listitem").filter({ hasText: "A 작업" })).toContainText("완료");
    await expect(page.getByRole("img", { name: /^A 작업:/ })).toHaveCount(3);
    const day = await page.getByLabel("날짜", { exact: true }).inputValue();
    await context.grantPermissions(["clipboard-read", "clipboard-write"]);
    const tomorrow = new Date(`${day}T12:00:00+09:00`);
    tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
    await page.clock.setFixedTime(tomorrow);
    await page.getByRole("button", { name: "어제 한 일 복사" }).click();
    await expect(page.getByRole("status")).toHaveText("복사했어요.");
    const report = await page.getByLabel("복사할 기록").inputValue();
    expect(report).toMatch(/- A 작업 \(.+\) · 완료/);
    expect(report).toMatch(/- B 요청 \(.+\) · 중단/);
    expect(report).toMatch(/- C 요청 \(.+\) · 중단/);
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(report);
});
